services:

############################
# MAIN
############################

  danvpn_image:
    build:
      context: .
      dockerfile: Dockerfile
    image: danvpn:latest
    container_name: danvpn-builder
    profiles: ["special"]

  bot:
    image: danvpn:latest
    container_name: danvpn-bot
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - /home/bot/vpn_dan_bot_docker/logs/:/vpn_dan_bot/logs
      - /home/bot/vpn_dan_bot_docker/bugs/:/vpn_dan_bot/bugs
      - /home/bot/vpn_dan_bot_docker/dumps/:/vpn_dan_bot/src/db/dumps
      - /home/bot/vpn_dan_bot_docker/backups/:/vpn_dan_bot/src/db/backups
      - /home/bot/vpn_dan_bot_docker/timepoint/:/vpn_dan_bot/src/scheduler/timepoint
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal:
        ipv4_address: "$BOT_HOST"
    command: ./_main.py
    restart: unless-stopped
    depends_on:
      - database
      - redis
      - website
    healthcheck:
      test: ["CMD-SHELL", "ps -ef | grep _main.py | grep -v grep || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

  website:
    image: danvpn:latest
    container_name: danvpn-website
    environment:
      TZ: "Europe/Moscow"
      TEST_WEB: "http://$WEB_HOST:$WEB_PORT/test"
    volumes:
      - /home/bot/vpn_dan_bot_docker/logs/:/vpn_dan_bot/logs
      - /home/bot/vpn_dan_bot_docker/bugs/:/vpn_dan_bot/bugs
      - /home/bot/vpn_dan_bot_docker/timepoint/:/vpn_dan_bot/src/scheduler/timepoint
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal:
        ipv4_address: "$WEB_HOST"
    command: ./_serv.py
    restart: unless-stopped
    depends_on:
      - nginx
      - database
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f $$TEST_WEB || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

############################
# DanVPN - SERVICES
############################

  database:
    image: postgres:14.17-alpine3.21
    container_name: danvpn-postgres
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_secret
      POSTGRES_DB: "$DB_NAME"
    secrets:
      - postgres_secret
    volumes:
      - /home/bot/vpn_dan_bot_docker/postgresql/data:/var/lib/postgresql/data
    networks:
      internal:
        ipv4_address: "$DB_HOST"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "export PGPASSWORD=$(cat /run/secrets/postgres_secret) && psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1'"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: danvpn-redis
    environment:
      TZ: "Europe/Moscow"
    secrets:
      - redis_secret
    volumes:
      - /home/bot/vpn_dan_bot_docker/redis/d–∞ta:/data
    networks:
      internal:
        ipv4_address: "$REDIS_HOST"
    command: ["sh", "-c", "redis-server --appendonly yes --requirepass \"$(cat /run/secrets/redis_secret)\" --replica-read-only no"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c",  "redis-cli -h localhost -a \"$(cat /run/secrets/redis_secret)\" ping | grep -q PONG || exit 1"]
      interval: 1m
      timeout: 3s
      retries: 5
      start_period: 3s

############################
# INSTRUMENTS
############################

  speedtest:
    build: ./src/iperf
    container_name: danvpn-speedtest
    profiles: ["special"]
    environment:
      TZ: "Europe/Moscow"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - wgnet

  pgadmin:
    # user: root
    image: dpage/pgadmin4:9.2.0
    container_name: pgadmin4
    environment:
      TZ: "Europe/Moscow"
      PGADMIN_LISTEN_PORT: "$PGADMIN_PORT"
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_USER"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASS}"            
      PGADMIN_SERVER_JSON_FILE: '/pgadmin4/servers.json'
      TEST_WEB: "$PGADMIN_HOST:$PGADMIN_PORT/pgadmin"
    secrets:
      - pgadmin_secret
    volumes:
        - ./servers.json:/pgadmin4/servers.json
    networks:
      internal:
        ipv4_address: "$PGADMIN_HOST"
    restart: unless-stopped
    depends_on:
      - nginx
      - database

  portainer:
    image: portainer/portainer-ce:2.27.3-alpine
    container_name: portainer
    environment:
      TZ: "Europe/Moscow"
      VIRTUAL_HOST: "$DANVPN_DOMAIN"
      VIRTUAL_PORT: "$PORTAINER_PORT"
      LETSENCRYPT_HOST: "$DANVPN_DOMAIN"
      LETSENCRYPT_EMAIL: "$ADMIN_MAIL"
    volumes:
      - /home/bot/vpn_dan_bot_docker/portainer_data:/data 
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal:
        ipv4_address: "$PORTAINER_HOST"
    restart: unless-stopped
    depends_on:
      - nginx

############################
# METRICS
############################

  influxdb:
    image: influxdb:2.7.11-alpine
    container_name: danvpn-influxdb
    environment:
      TZ: "Europe/Moscow"
      # DOCKER_INFLUXDB_INIT_MODE: setup
      # DOCKER_INFLUXDB_INIT_USERNAME: "$INFLUXDB_USER"
      # DOCKER_INFLUXDB_INIT_PASSWORD: "$INFLUXDB_PASS"
      # DOCKER_INFLUXDB_INIT_BUCKET: "$INFLUXDB_NAME"
      # DOCKER_INFLUXDB_INIT_ORG: "$INFLUXDB_ORG"
    volumes:
      - /home/bot/vpn_dan_bot_docker/influxdb/data:/var/lib/influxdb2 
      - /home/bot/vpn_dan_bot_docker/influxdb/config:/etc/influxdb2
    networks:
      metrics:
        ipv4_address: "$INFLUXDB_HOST"
    ports:
      - "8086:8086"
    restart: unless-stopped
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana:11.6.0-ubuntu
    container_name: danvpn-grafana
    environment:
      GF_SERVER_ROOT_URL: "https://$DANVPN_DOMAIN/grafana/"
    volumes:
      - /home/bot/vpn_dan_bot_docker/grafana:/var/lib/grafana
    user : '0'
    networks:
      metrics:
        ipv4_address: "$GRAFANA_HOST"
    # ports:
    #   - '3000:3000'
    restart: unless-stopped
    depends_on:
      - nginx

############################
# NETWORK
############################

  nginx:
    build: ./src/nginx
    container_name: danvpn-nginx
    environment:
      TZ: "Europe/Moscow"
      DOMAIN: "$DANVPN_DOMAIN"
      EMAIL: "$ADMIN_MAIL"
      TEST_WEB: "http://127.0.0.1/healthcheck"
    volumes:
      - /home/bot/vpn_dan_bot_docker/nginx/data:/etc/nginx
      - /home/bot/vpn_dan_bot_docker/nginx/certs:/etc/letsencrypt
    # network_mode: host
    networks:
      - internal
      - metrics
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f $$TEST_WEB || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/24
  wgnet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24

############################
# PASSWORDS
############################

secrets:
  postgres_secret:
    file: ./.secrets/postgres
  redis_secret:
    file: ./.secrets/redis
  pgadmin_secret:
    file: ./.secrets/pgadmin