services:

  ############################
  # MAIN
  ############################

  danvpn-init:
    build:
      context: .
      dockerfile: Dockerfile
    image: danvpn:latest
    container_name: danvpn-init
    user: "0"
    volumes:
      - $DANVPN_VOLUME/danvpn/logs/:/logs
      - $DANVPN_VOLUME/danvpn/bugs/:/bugs
      - $DANVPN_VOLUME/danvpn/dumps/:/dumps
      - $DANVPN_VOLUME/danvpn/backups/:/backups
      - $DANVPN_VOLUME/danvpn/timepoint/:/timepoint
    entrypoint: ["sh", "-c", "chown -R 1111:1111 /logs /bugs /dumps /backups /timepoint"]
    
  bot:
    image: danvpn:latest
    container_name: danvpn-bot
    user: "1111:1111"
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - $DANVPN_VOLUME/danvpn/logs/:/vpn_dan_bot/logs
      - $DANVPN_VOLUME/danvpn/bugs/:/vpn_dan_bot/bugs
      - $DANVPN_VOLUME/danvpn/dumps/:/vpn_dan_bot/src/db/dumps
      - $DANVPN_VOLUME/danvpn/backups/:/vpn_dan_bot/src/db/backups
      - $DANVPN_VOLUME/danvpn/timepoint/:/vpn_dan_bot/src/scheduler/timepoint
    networks:
      internal:
        ipv4_address: "$BOT_HOST"
    command: ./_main.py
    restart: unless-stopped
    depends_on:
      danvpn-init:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      website:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "ps -ef | grep _main.py | grep -v grep || exit 1" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  website:
    image: danvpn:latest
    container_name: danvpn-website
    user: "1111:1111"
    environment:
      TZ: "Europe/Moscow"
      TEST_WEB: "http://$WEB_HOST:$WEB_PORT/test"
    volumes:
      - $DANVPN_VOLUME/danvpn/logs/:/vpn_dan_bot/logs
      - $DANVPN_VOLUME/danvpn/bugs/:/vpn_dan_bot/bugs
      - $DANVPN_VOLUME/danvpn/timepoint/:/vpn_dan_bot/src/scheduler/timepoint
    networks:
      internal:
        ipv4_address: "$WEB_HOST"
    command: ./_serv.py
    restart: unless-stopped
    depends_on:
      danvpn-init:
        condition: service_completed_successfully
      nginx:
        condition: service_healthy
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f $$TEST_WEB || exit 1" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ############################
  # DanVPN - SERVICES
  ############################

  database-init:
    image: alpine:latest
    container_name: database-init
    user: "0"
    volumes:
      - $DANVPN_VOLUME/postgresql/data:/postgres
      - $DANVPN_VOLUME/redis/dаta:/redis
      - ./.config/database/init.sh:/usr/local/bin/init.sh
    entrypoint: ["sh", "-c", "/usr/local/bin/init.sh"]
    restart: "no"

  database:
    image: postgres:14.17-alpine3.21
    container_name: danvpn-postgres
    user: "2000:2000"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_secret
      POSTGRES_DB: "${DB_NAME}"
    secrets:
      - postgres_secret
    volumes:
      - $DANVPN_VOLUME/postgresql/data:/var/lib/postgresql/data
      # - ./.config/database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:ro
      - ./.config/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      internal:
        ipv4_address: "${DB_HOST}"
    # command: ["sh", "-c", "postgres -c hba_file=/etc/postgresql/pg_hba.conf"]
    restart: unless-stopped
    depends_on:
      database-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "psql", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-w", "-c", "SELECT 1;" ]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: danvpn-redis
    user: "3000:3000"
    environment:
      TZ: "Europe/Moscow"
    secrets:
      - redis_secret
    volumes:
      - $DANVPN_VOLUME/redis/dаta:/data
    networks:
      internal:
        ipv4_address: "$REDIS_HOST"
    command: [ "sh", "-c", "redis-server --appendonly yes --requirepass \"$(cat /run/secrets/redis_secret)\" --replica-read-only no --maxmemory 256mb --maxmemory-policy volatile-lru" ]
    restart: unless-stopped
    depends_on:
      database-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli -h localhost -a \"$(cat /run/secrets/redis_secret)\" ping | grep -q PONG || exit 1" ]
      interval: 1m
      timeout: 3s
      retries: 5
      start_period: 3s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ############################
  # INSTRUMENTS
  ############################

  speedtest: #TODO
    profiles: [ "special" ]
    build: ./src/iperf
    container_name: danvpn-speedtest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: "Europe/Moscow"
    networks:
      - wgnet
    # command: [ "sh", "-c", "iperf3 -O 1 -t 5 -Jc 172.31.0.1 || exit 1" ]

  create-tables:
    profiles: [ "special" ]
    image: danvpn:latest
    container_name: danvpn-db-create
    user: "1111:1111"
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - $DANVPN_VOLUME/danvpn/logs/:/vpn_dan_bot/logs
    networks:
      - internal
    command: .venv/bin/python ./src/scripts/db_recreate.py
    depends_on:
      danvpn-init:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    # image: nphung/pgadmin
    # image: fenglc/pgadmin4:2.1-python3.6-alpine
    container_name: pgadmin4
    user: "5050:5050"
    environment:
      TZ: "Europe/Moscow"
      PGADMIN_LISTEN_PORT: "${PGADMIN_PORT}"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_USER}"
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_secret
      PGADMIN_SERVER_JSON_FILE: '/pgadmin4/servers.json'
      TEST_WEB: "${PGADMIN_HOST}:${PGADMIN_PORT}/pgadmin"
    secrets:
      - pgadmin_secret
    volumes:
      - ./.config/servers.json:/pgadmin4/servers.json:ro
    networks:
      internal:
        ipv4_address: "${PGADMIN_HOST}"
    restart: unless-stopped
    depends_on:
      nginx:
        condition: service_healthy
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  portainer:
    # profiles: [ "special" ]
    image: portainer/portainer-ce:2.27.3-alpine
    container_name: portainer
    environment:
      TZ: "Europe/Moscow"
      VIRTUAL_HOST: "${DANVPN_DOMAIN}"
      VIRTUAL_PORT: "${PORTAINER_PORT}"
      LETSENCRYPT_HOST: "${DANVPN_DOMAIN}"
      LETSENCRYPT_EMAIL: "${ADMIN_MAIL}"
    volumes:
      - $DANVPN_VOLUME/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal:
        ipv4_address: "${PORTAINER_HOST}"
    restart: unless-stopped
    depends_on:
      nginx:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ############################
  # METRICS
  ############################
  
  metrics-init:
    image: alpine:latest
    container_name: metrics-init
    user: "0"
    volumes:
      - $DANVPN_VOLUME/grafana:/grafana
      - $DANVPN_VOLUME/influxdb/data:/influx_data
      - $DANVPN_VOLUME/influxdb/config:/influx_config
    entrypoint: [ "sh", "-c", "chown -R 472:472 /grafana /influx_data /influx_data" ]

  influxdb:
    image: influxdb:2.7.11-alpine
    container_name: danvpn-influxdb
    user: "472:472"
    environment:
      TZ: "Europe/Moscow"
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "${INFLUXDB_USER}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "${INFLUXDB_PASS}"
      DOCKER_INFLUXDB_INIT_BUCKET: "${INFLUXDB_NAME}"
      DOCKER_INFLUXDB_INIT_ORG: danvpn
      DOCKER_INFLUXDB_INIT_RETENTION: 90d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${INFLUX_ADMIN_TOKEN}"
    volumes:
      - $DANVPN_VOLUME/influxdb/data:/var/lib/influxdb2
      - $DANVPN_VOLUME/influxdb/config:/etc/influxdb2
    networks:
      metrics:
        ipv4_address: "$INFLUXDB_HOST"
    ports:
      - "8086:8086"
    restart: unless-stopped
    depends_on:
      metrics-init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:11.6.0-ubuntu
    container_name: danvpn-grafana
    user: "472:472"
    environment:
      TZ: "Europe/Moscow"
      GF_SERVER_ROOT_URL: "https://$DANVPN_DOMAIN/grafana/"
    volumes:
      - $DANVPN_VOLUME/grafana:/var/lib/grafana
    networks:
      metrics:
        ipv4_address: "${GRAFANA_HOST}"
    restart: unless-stopped
    depends_on:
      metrics-init:
        condition: service_completed_successfully
      nginx:
        condition: service_healthy
      influxdb:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ############################
  # NETWORK
  ############################

  nginx:
    build: ./src/nginx
    container_name: danvpn-nginx
    environment:
      TZ: "Europe/Moscow"
      DOMAIN: "${DANVPN_DOMAIN}"
      EMAIL: "${ADMIN_MAIL}"
      TEST_WEB: "http://127.0.0.1/healthcheck"
    volumes:
      - $DANVPN_VOLUME/nginx/certs:/etc/letsencrypt
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.config/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    networks:
      - internal
      - metrics
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f $$TEST_WEB || exit 1" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/24
  wgnet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24

############################
# PASSWORDS
############################

secrets:
  postgres_secret:
    file: ./.secrets/postgres
  redis_secret:
    file: ./.secrets/redis
  pgadmin_secret:
    file: ./.secrets/pgadmin