[tool.poetry]
name = "vpn_dan_bot"
version = "0.1.0"
description = ""
authors = ["zveropolis <zadira-era@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic-settings = "^2.4.0"
aiogram = "^3.11.0"
gitpython = "^3.1.43"
yoomoney = "^0.1.1"
requests = "^2.32.3"
sqlalchemy = "^2.0.32"
asyncpg = "^0.29.0"
psycopg = {extras = ["binary"], version = "^3.2.1"}
pandas = "^2.2.2"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
